# version: '3.8'

# Dev mode only!!!

services:

  emastan-auth:
    container_name: emastan-auth
    hostname: emastan-auth
    restart: unless-stopped
    build:
      context: ./
      # dockerfile: ./Dockerfile.dev
      dockerfile: ./Dockerfile
      args:
        - AUTH_PORT=9090
    command: uvicorn server:app --host 0.0.0.0 --ssl-keyfile /etc/ssl/private/key.pem --ssl-certfile /etc/ssl/certs/cert.pem --port 9090 --reload # 
    image: omarzos/emastan-auth
    environment:
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - AUTH_PORT=9090
      - API_SECRET_KEY=${SECRET_KEY}
      - API_ALGORITHM=${ALGORITHM}
      - AUTH_DATABASE_URL=sqlite:///../auth_db/auth_db_data.db
    ports:
      - 9090:9090
    volumes:
      - ./:/code
      - ./volumes/auth_db/:/auth_db/
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M


volumes:
  volumes:
    driver: local

